module.exports = {
  createUser: require("./createUser"),
  loadConversation: require("./loadConversation"),
  login: require("./login"),
  createOrUpdateMatch: require("./createOrUpdateMatch"),
  usersInLocation: require("./usersInLocation"),
  allUsers: require("./allUsers"),
  userSenderWithChat: require("./userSenderWithChat"),
  userMatchesWithChats: require("./userMatchesWithChats"),
  allVenues: require("./allUsers"),
  venuesInArea: require("./allVenues"),
  loadConversations: require("./loadConversations"),
  savePlayerId: require("./savePlayerId"),
  loadPlayerIds: require("./loadPlayerIds"),
  matchWithNotifications: require("./notifications/matchWithNotifications"),
  facebookLogin: require("./facebookLogin"),
  getUnreadConversationsCount: require("./getUnreadConversationsCount"),
  updateProfileOrCoverPhoto: require("./updateProfileOrCoverPhoto"),
  deletePhoto: require("./deletePhoto"),
  uploadPhoto: require("./uploadPhoto"),
  updateProfileBio: require("./updateProfileBio"),
  loadMoreMessages: require("./loadMoreMessages"),
  blockConversation: require("./blockConversation"),
  sendReportMail: require("./sendReportMail")
};
